apiVersion: v1
kind: Secret
metadata:
  namespace: spilons
  name: &cluster_name spilodemo
  labels:
    application: spilo
    spilo-cluster: *cluster_name
type: Opaque
data:
  superuser-password: emFsYW5kbw==
  replication-password: cmVwLXBhc3M=
  admin-password: YWRtaW4=
