apiVersion: v1
kind: ConfigMap
metadata:
  namespace: spilons
  name: spilo-config
data:
  # ETCD
  # Uncomment the following line if you want to use an external ETCD
  # ETCD_HOSTS: '"etcd-0.etcd:2379","etcd-1.etcd:2379","etcd-2.etcd:2379"'
  # Comment the following line if you want to use an external ETCD
  DCS_ENABLE_KUBERNETES_API: "true"
  KUBERNETES_SCOPE_LABEL: spilo-cluster
  KUBERNETES_ROLE_LABEL: role
  SPILO_CONFIGURATION: |
    bootstrap:
      initdb:
        - auth-host: md5
        - auth-local: trust
